// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Repository.DbContexts;

#nullable disable

namespace WebApp.Repository.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20250124100903_ProductSeed")]
    partial class ProductSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApp.Domain.Ksiazka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Kategoria")
                        .HasColumnType("int");

                    b.Property<string>("Tytul")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Autor = "Adolf",
                            Guid = new Guid("c6222742-2af4-45ce-aaf7-a170b90badd1"),
                            Kategoria = 1,
                            Tytul = "MeineKaumpf"
                        },
                        new
                        {
                            Id = 2,
                            Autor = "Adolf",
                            Guid = new Guid("a7569fde-9114-4e8b-b420-49da01967ea3"),
                            Kategoria = 1,
                            Tytul = "MeineKaumpf"
                        });
                });

            modelBuilder.Entity("WebApp.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description",
                            Guid = new Guid("f5af9cfb-caa7-4f7f-8223-5a1f15e5b073"),
                            Name = "Name"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description",
                            Guid = new Guid("814dde23-05d8-4fab-87a7-00d0f305e315"),
                            Name = "Mimi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
