// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Repository.DbContexts;

#nullable disable

namespace WebApp.Repository.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20250124101603_item")]
    partial class item
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApp.Domain.Ksiazka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Kategoria")
                        .HasColumnType("int");

                    b.Property<string>("Tytul")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Autor = "Adolf",
                            Guid = new Guid("e5e9debd-825c-4604-b8de-f53bceea17b4"),
                            Kategoria = 1,
                            Tytul = "MeineKaumpf"
                        },
                        new
                        {
                            Id = 2,
                            Autor = "Adolf",
                            Guid = new Guid("7c1b69c3-3045-49cf-960d-eee8c2968770"),
                            Kategoria = 1,
                            Tytul = "MeineKaumpf"
                        });
                });

            modelBuilder.Entity("WebApp.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description",
                            Guid = new Guid("608ef04e-5dbe-40cb-ad41-8f9b43ac45b5"),
                            Name = "Name"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description",
                            Guid = new Guid("accf3729-cc66-4b2b-a6ea-0056f0c1fd3b"),
                            Name = "Mimi"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description",
                            Guid = new Guid("05f6d081-fcfd-4bfa-b964-d719cb84a741"),
                            Name = "ututut"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
